### PR TITLE
Added Footer

### PR DESCRIPTION
**Pull request by Divyansh1315**
I've added the footer which will redirect to Ultirequiem.com. You can further add other footer links just by creating more 'li' tags.

### CODE REVIEW

**Comment by UltiRequiem** [comment]
That renders:



Maybe you are not running the development server? If you check the `Makefile` at the root of the project you can see

```Makefile
developlment:
	packup serve index.html
build:
	packup build index.html

.DEFAULT_GOAL := development
```

This project uses [packup](https://packup.deno.dev/getting-started/getting-started/) as bundler, so you must install [deno](https://deno.land), and then follow [packup](https://packup.deno.dev/getting-started/getting-started/) install instructions.

So to see how the page will build you must run on your terminal:

```sh
make
```
(If this does not work you don't have [`make`](https://en.wikipedia.org/wiki/Make_(software)) installed)

Then open in your browser `http://localhost:1234` and you will look at how the page really looks.

Also, the footer should be included in [`app.tsx`](https://github.com/UltiRequiem/ulticlock/blob/main/app.tsx) file, not in the HTML.

I guess you don't know about [React.js](https://www.reactjs.com) yet, which is okay, I can port what you did from HTML to the `app.tsx` file.

The footer looks very nice but I really don't want to add a CSS library, like bootstrap, for something so little like this, could you implement it with vanilla CSS?

Thanks for the PR! Ask anything you want 😊

**Comment by Divyansh1315** [comment]
I successfully installed deno but when I'm installing packup after that then it's showing - "The term 'deno' is not recognized as the name of a cmdlet, function, script file, or operable program."

**Comment by Divyansh1315** [comment]
Yes I'm currently new to React.

**Comment by Divyansh1315** [comment]
I successfully installed deno than packup also but when I'm running build command it's showing there is no such command.

**Comment by UltiRequiem** [comment]
> I successfully installed deno than packup also but when I'm running build command it's showing there is no such command.

There is not so command `make`/`packup`?

In case of `make`, run 
```sh
packup serve index.html
```

Is essentially the same, `make` is just an alias for that.

**Comment by UltiRequiem** [comment]
Oh

**Pull request closed without merging**
